### ISSUE TITLE
Bold the most pedagogical sentences

### ISSUE THREAD

**Issue by Pablohn26** [jawj/subtls#1]
I think this project is very pedagogical. Could you bold the pedagogical sentences to make easier to understand what is going on? 

For example the following: 

- We begin the TLS handshake by sending a client hello message 
- The server returns a response, and we parse it
- For the benefit of badly-written middleboxes that are following along expecting TLS 1.2, the server sends us a meaningless cipher change record:
- Both sides of the exchange now have everything they need to calculate the keys and IVs that will protect the rest of the handshake:
- ...

**Comment by jawj** [comment]
Thanks for the suggestion. I'm not 100% sure I want to do this — but we can keep the issue and see if people pile in on either side. 😄

**Comment by jawj** [comment]
OK, nobody has chimed in, so closing this for now.
