### ISSUE TITLE
Build failes because of inconsistent filename

### ISSUE THREAD

**Issue by linuskmr** [jawj/subtls#2]
In [startTLS.ts](https://github.com/jawj/subtls/blob/70c1500cacbd871a1fad39976d924990375355de/src/tls/startTls.ts#L3), the file `./tlsRecord` is imported: https://github.com/jawj/subtls/blob/70c1500cacbd871a1fad39976d924990375355de/src/tls/startTls.ts#L3

However, the file is actually named [tlsrecord.ts](https://github.com/jawj/subtls/blob/70c1500cacbd871a1fad39976d924990375355de/src/tls/tlsrecord.ts) (lowercase).

Therefore, trying to build the project results in the following error:

```
$ npm run build
...
> tsc --noEmit

src/tls/startTls.ts:3:92 - error TS2307: Cannot find module './tlsRecord' or its corresponding type declarations.

3 import { makeEncryptedTlsRecords, readEncryptedTlsRecord, readTlsRecord, RecordType } from './tlsRecord';
                                                                                             ~~~~~~~~~~~~~
Found 1 error in src/tls/startTls.ts:3
```

Renaming `tlsrecord.ts` to `tlsRecord.ts` fixes the problem for me.

**Comment by jawj** [comment]
Ah, oops. It had the right case locally, which I guess must mean I fixed it at some point, but I hadn't appreciated that Git defaulted to case-insensitive behaviour. Just fixed this in edf3388.
